### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by matthdsm** [nf-cmgg/sampletracking#3]
### Description of the bug

nf-test doesn't pick up the modules configuration resulting in passing, but broken tests

**Comment by matthdsm** [comment]
@nvnieuwk , would you mind taking a look what I'm doing wrong here?

**Comment by nvnieuwk** [comment]
Looks like an issue in your MultiQC module, is it up to date?

**Comment by matthdsm** [comment]
Fixed in #4
